name: Build and Push Docker Image

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push to Docker Hub
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: developer5rdl/rdl-frontend:latest

      - name: Save Docker image as tar
        run: |
          docker save developer5rdl/rdl-frontend:latest > digitaltwin-image.tar

      - name: Upload Image Artifact
        uses: actions/upload-artifact@v4
        with:
            name: digitaltwin-frontend-image
            path: digitaltwin-image.tar
            retention-days: 1

      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: 68.178.171.221
          username: rdltech
          password: ssR%Oc4C#V1B
          script: |
            # Create a directory for deployment and the compose file
            mkdir -p ~/digitaltwin-frontend-deploy
            cd ~/digitaltwin-frontend-deploy

            # Creating the docker-compose.yml on the VPS
            cat <<EOF > docker-compose.yml
            services:
              frontend-service:
                image: developer5rdl/rdl-frontend:latest
                container_name: rdl-frontend
                ports:
                  - "80:3000"
                restart: always
            EOF

            # Pull the image and deploy
            sudo docker compose down frontend-service || true
            sudo docker compose pull frontend-service
            sudo docker compose up -d frontend-service
