name: Build and Push Docker Image

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set lower case owner and repository name
        run: |
          echo "REPO_LOWER=${GITHUB_REPOSITORY,,}" >> ${GITHUB_ENV}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push to GHCR
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ghcr.io/${{ env.REPO_LOWER }}:latest

      - name: Save Docker image as tar
        run: |
          docker save ghcr.io/${{ env.REPO_LOWER }}:latest > digitaltwin-image.tar

      - name: Upload Image Artifact
        uses: actions/upload-artifact@v4
        with:
            name: digitaltwin-frontend-image
            path: digitaltwin-image.tar
            retention-days: 1
